### PR TITLE
Possible fix for Intel WiFi on mainline kernel

### PR DESCRIPTION
**Pull request by X4X5**
This PR is meant to fix the WiFi issue on mainline kernel 5.17.8. If there's anything that needs changing, please let me know

### CODE REVIEW

**Comment by cat-master21** [comment]
This works for me perfectly and **without** `backport-iwlwifi-dkms`. In addition, I've also test xanmod (based from linux kernel) kernel on 5.17.9 and it also works!

**Comment by X4X5** [comment]
It works without the package??? Well, I guess I'll keep the package up if it works, because then people who need the package won't have to worry about rolling back to the previous kernel to install it. I, however, don't have permission to merge pull requests, so someone else will have to merge

**Comment by cat-master21** [comment]
After some testing I was **not** able to install `backport-iwlwifi-dkms`. This could be because I used xanmod kernel but I'm not sure as Ubuntu counted it as an error

**Comment by X4X5** [comment]
Well, I'm able to install the package just fine on my machine, but I'm also using the Linux kernel. It could very well be your kernel version

**Comment by ajstrongdev** [comment]
I assume it is because you are not using the official Linux kernel. Can you test it with backport-iwlwifi-dkms as well and report your findings @cat-master21 - Furthermore, can we have this utilize kernel version 5.17.9 now that it has released? Many thanks.

**Comment by ajstrongdev** [comment]
I have just done some of my own testing on my Intel Wireless AX201 machine running Ubuntu 22.04 LTS - The problem seems to actually be the separate kernel module for iwlwifi, as when the kernel is installed without said module, it works fine and as intended. I will submit a PR to this branch and then once it has been committed and merged, I will release the new kernel to all running systems.

**Pull request merged**
