### PR TITLE
Styling, refactoring and two new features 

### PR DESCRIPTION
**Pull request by tricantivu**
Hi, I made some changes to the repository and here is a summary of them.

### *Styling changes:*

+ Use `||`  instead of a condition to shrink SLOC.
+ Use `-` to close apt's STDERR. 

### *New features:*

+ Use `|` and `-` characters to wrap the entire message after system upgrade. 
+ Change rhino-config's destination to follow [FHS](https://refspecs.linuxfoundation.org/FHS\_3.0/fhs-3.0.html#usrlocalLocalHierarchy) and prevent [issues](https://unix.stackexchange.com/a/8658) with the distribution.

### *Refactoring:*

Remove redundant use of mkdir before running `git clone` command since its manual states:

> *Clone a repository into a new directory*

### CODE REVIEW

**Comment by ajstrongdev** [comment]
I will test this shortly and see whether it works, thank you.

**Comment by cat-master21** [comment]
Currently rhino-update still uses $HOME directories which is not FHS compliant: https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch04s11.html#purpose26 it should be in `/usr/share/rhino/` @tricantivu

**Comment by tricantivu** [comment]
Hi @cat-master21.

I will overwrite my fork's history and make a commit to put rhino-config in `/usr/share/rhino` tomorrow it's quite late for me now.

**Comment by tricantivu** [comment]
Done making the changes.

**Comment by cat-master21** [comment]
What I mean't by my comment was the configuration to use `/usr/share/rhino/` not move rhino-config there as it isn't in $PATH.

**Comment by tricantivu** [comment]
I will just discard the changes of directory altogether. I'll fix this later, I'm currently out.

**Comment by cat-master21** [comment]
@tricantivu I think I will make rhino-update FHS complaint and all so don't worry about that.

**Pull request closed without merging**
