### PR TITLE
fix(update.sh): suppress apt warnings

### PR DESCRIPTION
**Pull request by cat-master21**

### CODE REVIEW

**Comment by cat-master21** [comment]
Current solution suppresses everything so a more in-depth is needed using `sed`.

**Comment by ajstrongdev** [comment]
At the moment I would not like to merge this, it suppresses everything which is not really what we want.

**Comment by cat-master21** [comment]
Yeah I know I plan to not use /dev/null and that is why this pr not ready for merge.

**Comment by cat-master21** [comment]
Yeah I know I plan to not use /dev/null and that is why this pr not ready for merge.

**Pull request merged**
