### PR TITLE
fix(update.sh): add missing `done`, check snaps/flatpaks, fallback to…

### PR DESCRIPTION
**Pull request by Elsie19**
… apt if nala is not installed

### CODE REVIEW

**Comment by ajstrongdev** [comment]
Will test tomorrow as it's late

**Review by ajstrongdev — CHANGES_REQUESTED** [review]
Test failed, does not go further than Kernel upgrade.

**Comment by Elsie19** [comment]
> Test failed, does not go further than Kernel upgrade.

Can you send the error?

**Comment by ajstrongdev** [comment]
> > Test failed, does not go further than Kernel upgrade.
> 
> Can you send the error?

There is no error. It just doesn't continue past installing the kernel.

**Comment by Elsie19** [comment]
Send a screenshot.

**Comment by ajstrongdev** [comment]
> Send a screenshot.

What screenshot can I send? The script just ends after the kernel installation. 
(PS: I also nuked my VM as i'm currently moving to a new OS)

**Comment by Elsie19** [comment]
In the script, replace the line `set -e` with `set -ex` and rerun.

**Comment by ajstrongdev** [comment]
Could you do that in a commit so I can test it with little intervention in a virtual machine as VMs are very irritating to work with with little dispensable RAM.

**Pull request merged**
